version: '3.7'
services:
  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "${ODOO_HOST}:${ODOO_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - odoo-network
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
